"""Fallakten der Kunden-Personas (docs/personas/kunden): Schaeden, Korrespondenz, Dokumente.

Handgeschriebene, fachlich konsistente Inhalte. Die Stufe ``persona_akten`` (synth/persona_akten.py)
macht daraus die Tabellen schaden, schaden_position, interaktion, dokument sowie gerenderte Dateien.

Konventionen: Datum ISO, Betraege in Landeswaehrung des Vertrags, IDs wie in den Persona-Dokumenten.
Mitarbeiter-IDs: MIT-00007 Amrein (Leistung Leben CH), MIT-00008 Wenger (UW HP CH), MIT-00009 Demirci
(Schaden HP DE), MIT-00012 Steinbrecher (Compliance DE), MIT-00013 Bianchi (Contact Center), MIT-00005 Jost
(Legal), MIT-00006 Lindqvist-Brandt (DSB), MIT-00010 Pfister (MLOps).
"""

from __future__ import annotations

# Jede Persona: {"schaeden": [...], "interaktionen": [...], "dokumente": [...]}
# schaden: id, vertrag, art, ursache, datum, meldung, kanal, plz, land, kurz, status, seit, reserve, bezahlt, regress,
#          deckung, ablehnung, sb, betrug_sichtbar, betrug_wahr, positionen[(art, betrag, datum, empfaenger, text)], waehrung, geschaedigter
# interaktion: id, kanal, richtung, zeit, mitarbeiter, vermittler, bezug_typ, bezug_id, thread, betreff, sprache, sentiment, text
# dokument: id, typ, richtung, format, datum, bezug (vertrag/schaden/antrag/interaktion), seiten, ocr, absender, empfaenger, titel, text

AKTEN: dict[str, dict] = {}

# ------------------------------------------------------------------------------------------------
# PTR-00000001 Simone Niederberger – Familie CH, App-Schaden automatisch reguliert, Skikollision Reto
# ------------------------------------------------------------------------------------------------
AKTEN["PTR-00000001"] = {
    "schaeden": [
        {"id": "SCH-00000110", "vertrag": "VTR-00000101", "art": "HP_PERSONEN", "ursache": "SKI_KOLLISION",
         "datum": "2019-02-16", "meldung": "2019-02-18", "kanal": "VERMITTLER", "plz": "3818", "land": "CH",
         "kurz": "Reto Niederberger kollidiert auf der Piste Grindelwald-First mit einer anderen Skifahrerin; Prellung Schulter und Skibruch der Geschaedigten.",
         "status": "GESCHLOSSEN", "seit": "2019-06-04", "reserve": 0.0, "bezahlt": 4180.0, "regress": 0.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": "MIT-00008", "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "CHF",
         "geschaedigter": "Dritte (Skifahrerin, Bern)",
         "positionen": [("RESERVE", 5000.0, "2019-02-19", None, "Erstreserve Personenschaden leicht"),
                        ("ZAHLUNG", 2980.0, "2019-04-12", "Geschaedigte", "Arztkosten und Selbstbehalt Krankenkasse"),
                        ("ZAHLUNG", 1200.0, "2019-05-28", "Geschaedigte", "Skiausruestung Zeitwert"),
                        ("RESERVE", 0.0, "2019-06-04", None, "Reserve aufgeloest, Fall geschlossen")]},
        {"id": "SCH-00000118", "vertrag": "VTR-00000101", "art": "HP_SACH", "ursache": "KIND_BESCHAEDIGT_FREMDSACHE",
         "datum": "2025-05-17", "meldung": "2025-05-18", "kanal": "APP", "plz": "6004", "land": "CH",
         "kurz": "Sohn Noah (8) stoesst beim Spielen das E-Bike des Nachbarn um; Display und Rahmen beschaedigt. Kostenvoranschlag Velohaendler CHF 2'340.",
         "status": "GESCHLOSSEN", "seit": "2025-05-21", "reserve": 0.0, "bezahlt": 2340.0, "regress": 0.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": None, "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "CHF",
         "geschaedigter": "Nachbar (Luzern)",
         "positionen": [("RESERVE", 2500.0, "2025-05-18", None, "Erstreserve automatisch (MINT Triage v3)"),
                        ("ZAHLUNG", 2340.0, "2025-05-21", "Nachbar", "Fast-Track-Zahlung nach Kostenvoranschlag, unter CHF 5'000"),
                        ("RESERVE", 0.0, "2025-05-21", None, "Automatisch geschlossen")]},
    ],
    "interaktionen": [
        {"id": "INT-00000412", "kanal": "APP", "richtung": "EINGEHEND", "zeit": "2025-05-18T09:14:00", "mitarbeiter": None, "vermittler": None,
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000118", "thread": "TH-00000118", "betreff": "Schadenmeldung E-Bike Nachbar", "sprache": "de",
         "sentiment": "neutral",
         "text": "Guten Tag\n\nGestern Nachmittag hat unser Sohn Noah (8) beim Spielen im Hof das E-Bike unseres Nachbarn umgestossen. Das Display ist gesprungen und der Rahmen hat einen Kratzer. Der Nachbar hat heute einen Kostenvoranschlag vom Velohaendler geholt, CHF 2'340. Ich lade drei Fotos und den Kostenvoranschlag hoch. Koennen Sie mir kurz sagen, ob das ueber unsere Privathaftpflicht laeuft?\n\nDanke fuer die schnelle Abwicklung.\nFreundliche Gruesse, Simone Niederberger"},
        {"id": "INT-00000413", "kanal": "CHAT", "richtung": "AUSGEHEND", "zeit": "2025-05-19T10:02:00", "mitarbeiter": "MIT-00013", "vermittler": None,
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000118", "thread": "TH-00000118", "betreff": "Rueckfrage zur Schadenmeldung", "sprache": "de",
         "sentiment": "neutral",
         "text": "Guten Tag Frau Niederberger\n\nDanke fuer die Meldung. Fuer die Pruefung brauche ich noch zwei Angaben: Wie alt ist Noah genau, und war ein Erwachsener beim Spielen anwesend? Das ist fuer die Frage der Aufsichtspflicht wichtig, aendert aber in der Regel nichts an der Deckung.\n\nFreundliche Gruesse\nDario Bianchi, Kundenservice Olten"},
        {"id": "INT-00000414", "kanal": "CHAT", "richtung": "EINGEHEND", "zeit": "2025-05-19T10:25:00", "mitarbeiter": "MIT-00013", "vermittler": None,
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000118", "thread": "TH-00000118", "betreff": "Re: Rueckfrage zur Schadenmeldung", "sprache": "de",
         "sentiment": "positiv",
         "text": "Noah ist am 23.11.2017 geboren, also 7, im November wird er 8. Ich war auf dem Balkon und habe es gesehen, mein Mann war im Haus. Danke fuer die schnelle Rueckmeldung."},
        {"id": "INT-00000415", "kanal": "APP", "richtung": "AUSGEHEND", "zeit": "2025-05-21T08:30:00", "mitarbeiter": None, "vermittler": None,
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000118", "thread": "TH-00000118", "betreff": "Ihr Schaden SCH-00000118 ist erledigt", "sprache": "de",
         "sentiment": None,
         "text": "Guten Tag Frau Niederberger\n\nIhr Schaden vom 17.05.2025 ist gedeckt. Wir haben CHF 2'340.00 gemaess Kostenvoranschlag an Ihren Nachbarn ueberwiesen. Es faellt kein Selbstbehalt an. Der Fall ist abgeschlossen.\n\nDiese Nachricht wurde automatisch erstellt.\nPfefferminzia Versicherungen AG"},
        {"id": "INT-00000517", "kanal": "APP", "richtung": "EINGEHEND", "zeit": "2025-11-24T19:40:00", "mitarbeiter": "MIT-00013", "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000104", "thread": "TH-00000517", "betreff": "Neue Vertragsnummer Vorsorge 3a", "sprache": "de",
         "sentiment": "neutral",
         "text": "Guten Tag\n\nIn der Jahresinformation steht eine neue Vertragsnummer fuer meine Saeule 3a. Gilt der alte Vertrag noch, oder ist das jetzt ein neuer Vertrag mit neuen Bedingungen? Koennen Sie mir kurz sagen, ob sich fuer mich etwas aendert?\n\nFreundliche Gruesse, Simone Niederberger"},
        {"id": "INT-00000518", "kanal": "APP", "richtung": "AUSGEHEND", "zeit": "2025-11-25T09:05:00", "mitarbeiter": "MIT-00013", "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000104", "thread": "TH-00000517", "betreff": "Re: Neue Vertragsnummer Vorsorge 3a", "sprache": "de",
         "sentiment": None,
         "text": "Guten Tag Frau Niederberger\n\nIhr Vertrag ist derselbe geblieben. Im November haben wir alle Lebensversicherungen aus dem alten System VERA in unser neues System uebernommen; dabei erhalten die Vertraege eine neue Nummer. Bedingungen, Praemie, Laufzeit und Bezugsrecht aendern sich nicht. Die alte Nummer bleibt als Referenz auf allen Dokumenten sichtbar.\n\nFreundliche Gruesse\nDario Bianchi, Kundenservice Olten"},
    ],
    "dokumente": [
        {"id": "DOK-00000101", "typ": "BERATUNGSPROTOKOLL", "richtung": "INTERN", "format": "MD", "datum": "2018-05-14", "bezug": ("vertrag", "VTR-00000102"),
         "seiten": 2, "ocr": "GUT", "absender": "Generalagentur Luzern", "empfaenger": "Akte",
         "titel": "Beratungsdokumentation Risikoleben Ehepaar Niederberger",
         "text": "Anlass: Geplante Hypothekaraufnahme fuer Eigenheim; Absicherung des Partnereinkommens bei Todesfall.\n\nBeduerfnisse: Beide Ehegatten erwerbstaetig (Simone 60 Prozent Physiotherapie, Reto 100 Prozent Projektleiter). Zwei Kinder (2014, 2017). Bestehende Vorsorge: Pensionskasse beide, keine private Todesfallabsicherung.\n\nEmpfehlung: Je eine Risikolebensversicherung ueber CHF 300'000, Laufzeit 25 Jahre, konstante Summe, Bezugsrecht der Ehepartner. Ueber-Kreuz-Gestaltung nicht noetig (CH, Ehegatten erbschaftssteuerbefreit im Kanton Luzern).\n\nEntscheid der Kunden: Beide Antraege gezeichnet, Gesundheitsfragen ohne Angaben, Nichtraucher.\n\nHinweis erteilt: Kundeninformation nach Art. 3 VVG, AVB PL-2017 ausgehaendigt.\n\nBeraterin: I. Roth-Fankhauser (in Vertretung Agenturleitung Luzern)"},
        {"id": "DOK-00000102", "typ": "BERATUNGSPROTOKOLL", "richtung": "INTERN", "format": "MD", "datum": "2023-06-20", "bezug": ("vertrag", "VTR-00000101"),
         "seiten": 2, "ocr": "GUT", "absender": "Generalagentur Luzern", "empfaenger": "Akte",
         "titel": "Beratungsdokumentation nach Hauskauf Rebhaldenweg 7",
         "text": "Anlass: Kauf Einfamilienhaus Rebhaldenweg 7, Luzern, per 01.06.2023.\n\nBesprochen: Erhoehung Risikoleben Reto von 300'000 auf 450'000 wegen hoeherer Hypothek; Baustein Gebaeudehaftpflicht in der Privathaftpflicht; Adressaenderung fuer alle Vertraege.\n\nEntscheid: Erhoehung Risikoleben Reto beantragt (Gesundheitspruefung folgt). Baustein Gebaeudehaftpflicht per 01.07.2023 eingeschlossen. Adressaenderung im System Leben erfasst; Haftpflicht wird nachgefuehrt.\n\nBemerkung: Kundin wuenscht kuenftig Kommunikation per App, Agentur bleibt Ansprechpartnerin fuer Beratung."},
        {"id": "DOK-00000103", "typ": "KOSTENVORANSCHLAG", "richtung": "EINGEHEND", "format": "MD", "datum": "2025-05-18", "bezug": ("schaden", "SCH-00000118"),
         "seiten": 1, "ocr": "GUT", "absender": "Velo Reuss GmbH, Luzern", "empfaenger": "Nachbar",
         "titel": "Kostenvoranschlag E-Bike Reparatur",
         "text": "Velo Reuss GmbH, Reussweg 3, 6003 Luzern, UID CHE-999.111.222\n\nKostenvoranschlag Nr. 2025-0517\nFahrzeug: E-Bike Trekking, Rahmen-Nr. WXT-4471\n\n1. Display-Einheit ersetzen        CHF 890.00\n2. Rahmenkratzer ausbessern, Lack   CHF 620.00\n3. Halterung Display, Kabelbaum     CHF 380.00\n4. Arbeit 4.5 h a CHF 100          CHF 450.00\n\nTotal inkl. MwSt. 8.1 Prozent    CHF 2'340.00\n\nGueltig 30 Tage."},
        {"id": "DOK-00000104", "typ": "SCHADENMELDUNG", "richtung": "EINGEHEND", "format": "MD", "datum": "2019-02-18", "bezug": ("schaden", "SCH-00000110"),
         "seiten": 2, "ocr": "MITTEL", "absender": "Reto Niederberger via Agentur", "empfaenger": "Pfefferminz Versicherung AG",
         "titel": "Schadenanzeige Privathaftpflicht Skikollision",
         "text": "Schadenanzeige Privathaftpflicht (Formular PF-S01, ausgefuellt durch Agentur)\n\nVersicherungsnehmerin: Niederberger Simone, Police 40.233.910\nVerursacher: Niederberger Reto (mitversicherter Ehegatte)\nSchadendatum: 16.02.2019, ca. 11:30 Uhr\nSchadenort: Grindelwald-First, Piste Nr. 4 (blau)\n\nHergang: Bei Nebel und schlechter Sicht fuhr Herr Niederberger auf eine vor ihm haltende Skifahrerin auf. Beide stuerzten. Die Geschaedigte klagte ueber Schmerzen in der rechten Schulter, ein Ski brach. Pistenrettung war vor Ort. Herr Niederberger blieb unverletzt.\n\nGeschaedigte: Frau B. S., Bern (Adresse in der Akte). Zeugen: Pistenrettung First.\nVerschulden aus Sicht des VN: eigenes Verschulden, zu schnell bei schlechter Sicht.\nPolizei: nein. Fotos: keine.\n\nUnterschrift VN: 18.02.2019"},
    ],
}

# ------------------------------------------------------------------------------------------------
# PTR-00000002 Jana Ortlepp – digital, Widerruf, Schluesselverlust, Chatbot-Fehler
# ------------------------------------------------------------------------------------------------
AKTEN["PTR-00000002"] = {
    "schaeden": [
        {"id": "SCH-00000210", "vertrag": "VTR-00000201", "art": "HP_MIETSACH", "ursache": "SCHLUESSELVERLUST",
         "datum": "2023-02-07", "meldung": "2023-02-07", "kanal": "APP", "plz": "04277", "land": "DE",
         "kurz": "Wohnungsschluessel mit Schliessanlagen-Schluessel im Zug verloren; Vermieter laesst Schliesszylinder ersetzen, EUR 780.",
         "status": "GESCHLOSSEN", "seit": "2023-02-09", "reserve": 0.0, "bezahlt": 780.0, "regress": 0.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": None, "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "EUR",
         "geschaedigter": "Vermieterin (Hausverwaltung Leipzig)",
         "positionen": [("RESERVE", 800.0, "2023-02-07", None, "Erstreserve automatisch"),
                        ("ZAHLUNG", 780.0, "2023-02-09", "Hausverwaltung", "Rechnung Schliesszylinder, Baustein Schluesselverlust"),
                        ("RESERVE", 0.0, "2023-02-09", None, "Automatisch geschlossen")]},
    ],
    "interaktionen": [
        {"id": "INT-00000201", "kanal": "CHAT", "richtung": "EINGEHEND", "zeit": "2021-03-15T21:12:00", "mitarbeiter": None, "vermittler": None,
         "bezug_typ": "ALLGEMEIN", "bezug_id": None, "thread": "TH-00000201", "betreff": "Chat mit Minzia-Assistent: Haftpflicht bei den Eltern", "sprache": "de",
         "sentiment": None,
         "text": "kunde: kurze frage, brauche ich eine eigene haftpflicht wenn ich noch bei meinen eltern wohne?\nassistent: Solange du in Ausbildung bist und im Haushalt deiner Eltern lebst, bist du in der Regel ueber deren Privathaftpflicht mitversichert. Mit dem ersten eigenen Job oder dem Auszug endet das meist. Soll ich dir eine Police vorbereiten, die du jederzeit widerrufen kannst?\nkunde: ok mach mal, ich schau mir das an\nassistent: Erledigt. Dein Antrag ist vorbereitet, du kannst ihn in der App abschliessen. Widerruf ist innerhalb von 14 Tagen ohne Angabe von Gruenden moeglich."},
        {"id": "INT-00000202", "kanal": "EMAIL", "richtung": "EINGEHEND", "zeit": "2021-03-24T08:03:00", "mitarbeiter": None, "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000203", "thread": "TH-00000202", "betreff": "Widerruf Vertrag MZ-2021-000203-P", "sprache": "de",
         "sentiment": "neutral",
         "text": "Sehr geehrte Damen und Herren,\n\nhiermit widerrufe ich den am 15.03.2021 geschlossenen Vertrag ueber eine Privathaftpflichtversicherung (Policennummer MZ-2021-000203-P) fristgerecht. Bitte bestaetigen Sie mir den Widerruf und erstatten Sie den bereits gezahlten Beitrag.\n\nMit freundlichen Gruessen\nJana Ortlepp"},
        {"id": "INT-00000203", "kanal": "EMAIL", "richtung": "AUSGEHEND", "zeit": "2021-03-24T08:04:00", "mitarbeiter": None, "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000203", "thread": "TH-00000202", "betreff": "Re: Widerruf Vertrag MZ-2021-000203-P", "sprache": "de",
         "sentiment": None,
         "text": "Hallo Jana,\n\ndein Widerruf ist angekommen und wirksam. Den Beitrag von EUR 1.45 fuer die neun Tage erstatten wir auf dein Konto. Wenn du spaeter doch eine eigene Haftpflicht brauchst, bist du mit zwei Klicks zurueck.\n\nDein Team von minzia.direct\n\n(automatisch erstellt)"},
        {"id": "INT-00000230", "kanal": "CHAT", "richtung": "EINGEHEND", "zeit": "2024-11-18T22:40:00", "mitarbeiter": None, "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000201", "thread": "TH-00000230", "betreff": "Chat: Versicherungsschutz Portugal", "sprache": "de",
         "sentiment": None,
         "text": "kunde: bin ich im urlaub in portugal versichert? fliege naechste woche\nassistent: Ja. Deine Privathaftpflicht (Bedingungen MZ-DIRECT, Ziffer A3) gilt weltweit bei voruebergehendem Aufenthalt bis zu einem Jahr. Schaeden, die du in Portugal verursachst, sind gedeckt; Mietsachschaeden an der Ferienunterkunft ebenfalls bis EUR 50'000.\nkunde: passt, danke"},
        {"id": "INT-00000241", "kanal": "CHAT", "richtung": "EINGEHEND", "zeit": "2025-04-14T18:15:00", "mitarbeiter": None, "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000201", "thread": "TH-00000241", "betreff": "Chat: Umstellung auf Pfefferminzia App", "sprache": "de",
         "sentiment": None,
         "text": "kunde: ihr habt mir gemailt dass minzia.direct jetzt pfefferminzia app heisst. aendern sich meine bedingungen?\nassistent: Nein. Dein Vertrag laeuft mit den Bedingungen der Generation MZ-DIRECT weiter, an Deckung, Beitrag und Kuendigungsfrist aendert sich nichts. Neu ist nur die App und dass hinter dem Vertrag jetzt die Pfefferminzia Versicherung AG als Risikotraeger steht.\nkunde: ok"},
        {"id": "INT-00000255", "kanal": "CHAT", "richtung": "EINGEHEND", "zeit": "2025-09-08T20:31:00", "mitarbeiter": None, "vermittler": None,
         "bezug_typ": "ALLGEMEIN", "bezug_id": None, "thread": "TH-00000255", "betreff": "Chat: Risikoleben nach Wohnungskauf", "sprache": "de",
         "sentiment": None,
         "text": "kunde: ich hab jetzt eine wohnung gekauft mit kredit. brauche ich eine risikoleben?\nassistent: Eine Risikolebensversicherung zahlt im Todesfall eine vereinbarte Summe aus, zum Beispiel um einen Kredit abzuloesen. Sinnvoll ist sie, wenn jemand von deinem Einkommen abhaengt oder der Kredit sonst nicht bedient werden koennte. Fuer EUR 200'000 ueber 30 Jahre liegt der monatliche Beitrag als Nichtraucherin in deinem Alter bei rund 15 Euro. Der Antrag dauert etwa zehn Minuten, mit Gesundheitsfragen.\nkunde: ok zeig mir den antrag"},
        {"id": "INT-00000262", "kanal": "CHAT", "richtung": "EINGEHEND", "zeit": "2025-11-03T12:10:00", "mitarbeiter": "MIT-00010", "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000202", "thread": "TH-00000262", "betreff": "Chat: Steuerbescheinigung Risikoleben (Fehlantwort)", "sprache": "de",
         "sentiment": "negativ",
         "text": "kunde: bekomme ich fuer die risikoleben eine steuerbescheinigung fuer die steuererklaerung?\nassistent: Ja, wir stellen dir jaehrlich eine Bescheinigung ueber die geleisteten Beitraege aus. Die Beitraege zur Rentenversicherung kannst du als Altersvorsorgeaufwendungen nach Paragraph 10 EStG bis zum Hoechstbetrag absetzen; die Bescheinigung findest du ab Februar in der App.\nkunde: das stimmt nicht, oder? das ist keine rentenversicherung\nassistent: Du hast recht, ich habe die Produkte verwechselt. Beitraege zu einer Risikolebensversicherung sind nur im Rahmen der sonstigen Vorsorgeaufwendungen absetzbar, deren Hoechstbetrag meist schon durch die Krankenversicherung ausgeschoepft ist. Eine Bescheinigung stellen wir auf Wunsch trotzdem aus.\n\n[Feedback-Button: Antwort falsch. Ticket an Data & AI Office, Fehlerprotokoll LLM-2025-1103-07]"},
    ],
    "dokumente": [
        {"id": "DOK-00000201", "typ": "ANTRAG", "richtung": "EINGEHEND", "format": "MD", "datum": "2025-09-09", "bezug": ("vertrag", "VTR-00000202"),
         "seiten": 3, "ocr": "GUT", "absender": "Jana Ortlepp (App)", "empfaenger": "Pfefferminzia Lebensversicherung Deutschland AG",
         "titel": "Digitaler Antrag RisikoLeben (JSON-Export der App)",
         "text": "{\n  \"antrag\": \"ANT-00000202\",\n  \"produkt\": \"term_life\",\n  \"versicherungssumme\": 200000,\n  \"laufzeit_jahre\": 30,\n  \"summenverlauf\": \"KONSTANT\",\n  \"antragstellerin\": {\"name\": \"Jana Ortlepp\", \"geburtsdatum\": \"1996-08-22\", \"beruf\": \"UX-Designerin\", \"raucherin\": false},\n  \"gesundheitsfragen\": [\n    {\"id\": \"GF-2025-01\", \"frage\": \"Groesse / Gewicht\", \"antwort\": \"168 cm / 61 kg\"},\n    {\"id\": \"GF-2025-04\", \"frage\": \"Waren Sie in den letzten 5 Jahren wegen einer Erkrankung in aerztlicher Behandlung?\", \"antwort\": \"JA\", \"freitext\": \"vor 2 Jahren Physio wegen Rueckenschmerzen, seither nichts\"},\n    {\"id\": \"GF-2025-07\", \"frage\": \"Bestehen Erkrankungen des Herz-Kreislauf-Systems?\", \"antwort\": \"NEIN\"},\n    {\"id\": \"GF-2025-12\", \"frage\": \"Nehmen Sie regelmaessig Medikamente?\", \"antwort\": \"NEIN\"}\n  ],\n  \"bezugsrecht\": \"gesetzliche Erben\",\n  \"e_signatur\": \"2025-09-09T20:44:12Z\",\n  \"uw_entscheid\": {\"code\": \"N\", \"automatisiert\": true, \"engine\": \"MINT Underwriting-Engine v2\"}\n}"},
        {"id": "DOK-00000202", "typ": "RECHNUNG", "richtung": "EINGEHEND", "format": "MD", "datum": "2023-02-08", "bezug": ("schaden", "SCH-00000210"),
         "seiten": 1, "ocr": "GUT", "absender": "Hausverwaltung Leipzig-Sued GmbH", "empfaenger": "Jana Ortlepp",
         "titel": "Rechnung Ersatz Schliesszylinder",
         "text": "Hausverwaltung Leipzig-Sued GmbH\nRechnung 2023-0214 vom 08.02.2023\n\nObjekt: Holunderstieg 12, 04277 Leipzig, WE 3\nAnlass: Verlust Wohnungsschluessel mit Schliessanlagenfunktion am 07.02.2023\n\nErsatz Schliesszylinder Wohnungstuer und Haustuer (Schliessanlage), 2 Stueck   EUR 540.00\nMontage Schluesseldienst                                                   EUR 240.00\nGesamt                                                                     EUR 780.00\n\nZahlbar innert 14 Tagen."},
    ],
}

# ------------------------------------------------------------------------------------------------
# PTR-00000003 Schreinerei Kaufmann + Soehne – Grossschaden Wasser, Regress, Sanierung
# ------------------------------------------------------------------------------------------------
AKTEN["PTR-00000003"] = {
    "schaeden": [
        {"id": "SCH-00000310", "vertrag": "VTR-00000301", "art": "HP_SACH", "ursache": "BEARBEITUNGSSCHADEN",
         "datum": "2018-11-05", "meldung": "2018-11-07", "kanal": "VERMITTLER", "plz": "5600", "land": "CH",
         "kurz": "Kratzer im Parkett einer Kundenwohnung bei Kuechenmontage; Ausbesserung durch Bodenleger CHF 1'900.",
         "status": "GESCHLOSSEN", "seit": "2018-12-20", "reserve": 0.0, "bezahlt": 1900.0, "regress": 0.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": "MIT-00008", "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "CHF",
         "geschaedigter": "Kundin der Schreinerei (Lenzburg)",
         "positionen": [("RESERVE", 2500.0, "2018-11-08", None, "Erstreserve Bearbeitungsschaden"),
                        ("ZAHLUNG", 1900.0, "2018-12-18", "Geschaedigte", "Rechnung Bodenleger abzueglich Selbstbehalt CHF 500, SB vom VN eingefordert"),
                        ("RESERVE", 0.0, "2018-12-20", None, "geschlossen")]},
        {"id": "SCH-00000318", "vertrag": "VTR-00000301", "art": "HP_SACH", "ursache": "WASSERSCHADEN_INSTALLATION",
         "datum": "2024-03-12", "meldung": "2024-03-13", "kanal": "VERMITTLER", "plz": "5600", "land": "CH",
         "kurz": "Undichter Wasseranschluss nach Kuechenmontage in Neubauwohnung; Wasser dringt ueber Nacht in die Wohnung und zwei darunterliegende Wohnungen. Bauschaden, Mobiliar, Mietausfall.",
         "status": "GESCHLOSSEN", "seit": "2025-03-18", "reserve": 0.0, "bezahlt": 172400.0, "regress": 40000.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": "MIT-00008", "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "CHF",
         "geschaedigter": "Stockwerkeigentuemergemeinschaft Aarepark, Lenzburg",
         "positionen": [("RESERVE", 120000.0, "2024-03-20", None, "Erstreserve nach Besichtigung, Gutachter beauftragt"),
                        ("KOSTEN", 6800.0, "2024-05-14", "Gutachter", "Bauschadengutachten"),
                        ("RESERVE", 180000.0, "2024-05-15", None, "Reserve nach Gutachten auf Ultimate 180'000 erhoeht"),
                        ("ZAHLUNG", 95000.0, "2024-09-02", "STWEG Aarepark", "Teilzahlung Bauschaden, Freigabe Teamleitung Schaden CH"),
                        ("ZAHLUNG", 48600.0, "2025-01-20", "STWEG Aarepark", "Mobiliar und Mietausfall Wohnungen 2 und 3"),
                        ("ZAHLUNG", 22000.0, "2025-03-10", "STWEG Aarepark", "Restzahlung Bauschaden nach Schlussrechnung"),
                        ("RESERVE", 0.0, "2025-03-18", None, "Fall geschlossen, Gesamtaufwand 172'400 inkl. Kosten"),
                        ("REGRESS", -40000.0, "2025-07-08", "Armaturenlieferant", "Regressvergleich Produktfehler Armatur, Eingang")]},
    ],
    "interaktionen": [
        {"id": "INT-00000318", "kanal": "EMAIL", "richtung": "EINGEHEND", "zeit": "2024-03-13T07:52:00", "mitarbeiter": "MIT-00008", "vermittler": "VRM-00042",
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000318", "thread": "TH-00000318", "betreff": "Schadenmeldung Kaufmann + Soehne, Wasserschaden Lenzburg, dringend", "sprache": "de",
         "sentiment": "negativ",
         "text": "Sehr geehrte Damen und Herren\n\nIm Namen unserer Kundin Schreinerei Kaufmann + Soehne GmbH (Police 40.551.207-2) melden wir einen Wasserschaden in einer Neubauwohnung in Lenzburg (Aarepark, Wohnung 4.2). Nach der Kuechenmontage vom 11.03. ist ueber Nacht Wasser aus dem Anschluss der Spuele ausgetreten. Betroffen sind die Wohnung selbst sowie zwei darunterliegende Wohnungen (Decken, Boeden, Mobiliar). Die Stockwerkeigentuemer haben eine Sanierungsfirma beauftragt; erste Schaetzung liegt bei CHF 150'000 bis 200'000.\n\nWir bitten um umgehende Besichtigung durch einen Gutachter und um Bestaetigung der Deckung bis Freitag. Der Bauherr droht bereits mit rechtlichen Schritten gegen unsere Kundin.\n\nFreundliche Gruesse\nBroker Mittelland AG, Aarau"},
        {"id": "INT-00000319", "kanal": "TELEFON", "richtung": "EINGEHEND", "zeit": "2024-03-13T10:15:00", "mitarbeiter": "MIT-00008", "vermittler": None,
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000318", "thread": "TH-00000318", "betreff": "Telefonnotiz VN Bruno Kaufmann", "sprache": "de",
         "sentiment": "negativ",
         "text": "Tel. VN B. Kaufmann, 10 Min. Sehr aufgebracht. Sagt, Armatur sei vom Lieferanten geliefert, Montage nach Anleitung, Anschluss habe am Abend dicht gewirkt. Fragt, ob er die Kundin selbst entschaedigen soll (NEIN, keine Anerkennung ohne uns). Regress gegen Lieferant pruefen. Gutachter Baumann & Co beauftragt, Besichtigung Fr. 15.03."},
        {"id": "INT-00000325", "kanal": "EMAIL", "richtung": "EINGEHEND", "zeit": "2024-06-11T16:40:00", "mitarbeiter": "MIT-00008", "vermittler": "VRM-00042",
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000318", "thread": "TH-00000318", "betreff": "Wasserschaden Aarepark: Stand der Regulierung", "sprache": "de",
         "sentiment": "negativ",
         "text": "Sehr geehrter Herr Wenger\n\nDas Gutachten liegt seit dem 14.05. vor und beziffert den Schaden auf CHF 180'000. Seither ist keine Zahlung erfolgt. Die Stockwerkeigentuemer haben unserer Kundin gestern eine Frist bis 30.06. gesetzt und kuendigen andernfalls Klage an. Unsere Kundin ist ein Betrieb mit 14 Mitarbeitenden und kann eine Klage nicht tragen.\n\nWir erwarten Ihre Stellungnahme bis 18.06. mit einem verbindlichen Zahlungsplan. Sollte die Regulierung weiter verzoegert werden, behalten wir uns vor, die Ombudsstelle einzuschalten.\n\nFreundliche Gruesse\nBroker Mittelland AG"},
        {"id": "INT-00000326", "kanal": "EMAIL", "richtung": "AUSGEHEND", "zeit": "2024-06-14T11:05:00", "mitarbeiter": "MIT-00008", "vermittler": "VRM-00042",
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000318", "thread": "TH-00000318", "betreff": "Re: Wasserschaden Aarepark: Stand der Regulierung", "sprache": "de",
         "sentiment": None,
         "text": "Sehr geehrte Damen und Herren\n\nDie Deckung ist bestaetigt, die Haftung dem Grunde nach anerkannt. Offen ist die Frage, ob die Armatur einen Produktfehler hatte; das aendert nichts an der Zahlung an die Geschaedigten, wohl aber am Regress. Wir schlagen vor: Teilzahlung von CHF 95'000 an die Stockwerkeigentuemergemeinschaft bis Ende August auf Basis der bisherigen Sanierungsrechnungen, Rest nach Schlussrechnung. Die Freigabe der Teilzahlung erfolgt durch die Teamleitung, da der Betrag ueber meiner Kompetenz liegt.\n\nFreundliche Gruesse\nTobias Wenger, Senior Underwriter, in Vertretung Schaden CH"},
        {"id": "INT-00000340", "kanal": "EMAIL", "richtung": "EINGEHEND", "zeit": "2025-02-10T09:20:00", "mitarbeiter": "MIT-00008", "vermittler": "VRM-00042",
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000301", "thread": "TH-00000340", "betreff": "Anfrage Hoeherdeckung CHF 10 Mio. Kaufmann + Soehne", "sprache": "de",
         "sentiment": "neutral",
         "text": "Sehr geehrter Herr Wenger\n\nUnsere Kundin hat den Zuschlag fuer den Innenausbau des Schulhauses Lenzburg-Nord erhalten (Auftragsvolumen CHF 1.8 Mio.). Der Bauherr verlangt eine Deckungssumme von CHF 10 Mio. Bitte unterbreiten Sie uns eine Offerte inkl. Bearbeitungsschaeden mit Sublimit CHF 2 Mio.\n\nWir weisen darauf hin, dass die Praemie nach der Sanierung im November bereits um 20 Prozent gestiegen ist.\n\nFreundliche Gruesse\nBroker Mittelland AG"},
    ],
    "dokumente": [
        {"id": "DOK-00000301", "typ": "GUTACHTEN", "richtung": "EINGEHEND", "format": "MD", "datum": "2024-05-14", "bezug": ("schaden", "SCH-00000318"),
         "seiten": 14, "ocr": "GUT", "absender": "Baumann & Co Bauschadengutachten AG, Aarau", "empfaenger": "Pfefferminz Versicherung AG, Schaden CH",
         "titel": "Bauschadengutachten Wasserschaden Aarepark Lenzburg",
         "text": "1. Auftrag: Feststellung von Ursache und Umfang des Wasserschadens vom 11./12.03.2024 in der Ueberbauung Aarepark, Lenzburg, Wohnungen 4.2, 3.2 und 2.2.\n\n2. Besichtigung: 15.03.2024 und 09.04.2024 in Anwesenheit des Verwalters, des Kuechenbauers (M. Kaufmann) und des Sanierungsunternehmers.\n\n3. Ursache: Der flexible Anschlussschlauch der Kuechenarmatur (Fabrikat Aquaflex 3/8, Charge 23-11) war am Uebergang zum Eckventil undicht. Die Verschraubung war fachgerecht angezogen; der Dichtring zeigt eine Fertigungsunregelmaessigkeit (unvollstaendige Vulkanisation). Ein Montagefehler ist nicht nachweisbar. Eine Mitursache durch fehlende Dichtheitsprobe unter Druck ueber Nacht ist moeglich.\n\n4. Umfang:\n   Wohnung 4.2: Unterlagsboden und Parkett Kueche/Wohnen 62 m2, Sockelleisten, Kuechenunterschraenke        CHF 71'400\n   Wohnung 3.2: Decke Gips, Malerarbeiten, Parkett 38 m2, Mobiliar (Sofa, Teppich)                          CHF 54'200\n   Wohnung 2.2: Decke, Malerarbeiten, Trocknung                                                             CHF 21'900\n   Trocknung und Bautrockner 6 Wochen, Notdienst                                                            CHF 14'300\n   Mietausfall Wohnungen 3.2 und 2.2 (je 2 Monate)                                                          CHF 11'200\n   Nebenkosten, Bauleitung Sanierung                                                                        CHF 7'000\n   Total geschaetzt                                                                                        CHF 180'000\n\n5. Empfehlung: Regress gegen den Armaturenlieferanten pruefen (Produktfehler Dichtring). Beweissicherung: Schlauch und Dichtring sichergestellt, Fotos 1 bis 42 im Anhang."},
        {"id": "DOK-00000302", "typ": "KORRESPONDENZ", "richtung": "AUSGEHEND", "format": "MD", "datum": "2024-11-18", "bezug": ("vertrag", "VTR-00000301"),
         "seiten": 2, "ocr": "GUT", "absender": "Pfefferminz Versicherung AG, Underwriting Haftpflicht CH", "empfaenger": "Broker Mittelland AG",
         "titel": "Sanierung Betriebshaftpflicht Kaufmann + Soehne per 01.01.2025",
         "text": "Sehr geehrte Damen und Herren\n\nNach dem Grossschaden vom 12.03.2024 (Gesamtaufwand voraussichtlich CHF 172'400) haben wir den Vertrag 40.551.207-2 geprueft. Die Schadenquote der letzten drei Jahre liegt bei 810 Prozent. Wir fuehren den Vertrag weiter, passen ihn aber per Hauptfaelligkeit 01.01.2025 wie folgt an:\n\n- Jahrespraemie neu CHF 4'620.00 (bisher CHF 3'840.00), das entspricht einem Zuschlag von 20 Prozent gemaess Tarifhandbuch Kapitel 3 (Schadenquote ueber 80 Prozent).\n- Selbstbehalt fuer Bearbeitungs- und Obhutsschaeden neu CHF 2'000 je Ereignis (bisher CHF 500).\n- Auflage: Dichtheitspruefung unter Betriebsdruck fuer mindestens 12 Stunden nach jeder Wasseranschlussmontage, dokumentiert im Montageprotokoll.\n\nDie Aenderungen erfolgen unter der Kompetenzstufe U4. Sollte Ihre Kundin die Anpassung nicht akzeptieren, steht ihr das ordentliche Kuendigungsrecht zur Hauptfaelligkeit zu.\n\nFreundliche Gruesse\nTobias Wenger, Senior Underwriter Betriebs- und Berufshaftpflicht CH"},
        {"id": "DOK-00000303", "typ": "VERGLEICH", "richtung": "EINGEHEND", "format": "MD", "datum": "2025-07-08", "bezug": ("schaden", "SCH-00000318"),
         "seiten": 2, "ocr": "GUT", "absender": "Aquaflex Sanitaertechnik AG, Rechtsdienst", "empfaenger": "Pfefferminzia Versicherungen AG, Regress",
         "titel": "Vergleichsvereinbarung Regress Wasserschaden Aarepark",
         "text": "Vergleichsvereinbarung\n\nzwischen Pfefferminzia Versicherung AG, Olten (Regressglaeubigerin) und Aquaflex Sanitaertechnik AG, Zuerich (Regressschuldnerin)\n\n1. Die Regressschuldnerin anerkennt ohne Praejudiz fuer weitere Faelle, dass der Anschlussschlauch Aquaflex 3/8 der Charge 23-11 eine Fertigungsunregelmaessigkeit aufwies.\n2. Die Regressschuldnerin bezahlt zur Abgeltung saemtlicher Regressansprueche aus dem Schadenereignis vom 12.03.2024 (Aarepark Lenzburg) den Betrag von CHF 40'000.00 bis 31.07.2025.\n3. Mit Zahlung sind alle gegenseitigen Ansprueche aus diesem Ereignis per Saldo aller Ansprueche erledigt.\n4. Die Parteien bewahren Stillschweigen ueber den Inhalt dieser Vereinbarung.\n\nZuerich, 08.07.2025 / Olten, 10.07.2025"},
        {"id": "DOK-00000304", "typ": "AKTENNOTIZ", "richtung": "INTERN", "format": "MD", "datum": "2024-09-02", "bezug": ("schaden", "SCH-00000318"),
         "seiten": 1, "ocr": "GUT", "absender": "Schaden CH", "empfaenger": "Akte",
         "titel": "Bearbeitungsjournal SCH-00000318 (Auszug SILAS)",
         "text": "13.03.24 TW  Meldung via Broker, Grossschaden, Res. 120k vorl. Gutachter Baumann beauftragt.\n15.03.24 TW  Besichtigung. Ursache vermutl. Armatur. Regress pruefen. VN sehr nervoes, Broker drueckt.\n20.03.24 TW  Res. 120'000 gebucht. GS-Meldung an Grossschadenkomitee (Schwelle 100k).\n14.05.24 TW  Gutachten: 180k, Produktfehler Dichtring wahrscheinlich. Res. auf 180k. Regress an REG weitergeleitet.\n11.06.24 TW  Broker droht mit Ombudsstelle. Hftg. dem Grunde nach bejaht, Deckung ok. Teilzahlung 95k vorbereitet.\n02.09.24 AD  Freigabe Teilzahlung 95'000 durch TL Schaden CH (ueber Kompetenz SB 25k). Zahlung ausgeloest.\n18.11.24 TW  Sanierung UW: +20 Prozent, SB 2'000, Auflage Dichtheitspruefung. Broker informiert.\n20.01.25 AD  Mobiliar/Mietausfall 48'600 bezahlt.\n10.03.25 AD  Schlussrechnung, Rest 22'000. Total 172'400 inkl. Gutachterkosten. Fall schliessen.\n08.07.25 REG Regressvergleich Aquaflex 40'000. Eingang 28.07."},
    ],
}

# ------------------------------------------------------------------------------------------------
# PTR-00000004 Bergmann Gebaeudetechnik – Photovoltaik-Schaden, unangezeigte Gefahrerhoehung
# ------------------------------------------------------------------------------------------------
AKTEN["PTR-00000004"] = {
    "schaeden": [
        {"id": "SCH-00000410", "vertrag": "VTR-00000401", "art": "HP_SACH", "ursache": "BEARBEITUNGSSCHADEN",
         "datum": "2017-08-22", "meldung": "2017-08-24", "kanal": "VERMITTLER", "plz": "01796", "land": "DE",
         "kurz": "Monteur beschaedigt beim Bohren eine Fussbodenheizung in einer Kundenwohnung; Reparatur und Estrichoeffnung EUR 6'400.",
         "status": "GESCHLOSSEN", "seit": "2017-11-02", "reserve": 0.0, "bezahlt": 6400.0, "regress": 0.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": "MIT-00009", "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "EUR",
         "geschaedigter": "Kunde des Betriebs (Pirna)",
         "positionen": [("RESERVE", 7000.0, "2017-08-25", None, "Erstreserve"), ("ZAHLUNG", 6400.0, "2017-10-30", "Geschaedigter", "Reparaturrechnung Heizungsbauer und Estrich, SB 500 vom VN eingefordert"),
                        ("RESERVE", 0.0, "2017-11-02", None, "geschlossen")]},
        {"id": "SCH-00000414", "vertrag": "VTR-00000401", "art": "HP_SACH", "ursache": "WASSERSCHADEN_INSTALLATION",
         "datum": "2020-12-03", "meldung": "2020-12-04", "kanal": "VERMITTLER", "plz": "01796", "land": "DE",
         "kurz": "Wasserschaden nach Heizungsumbau in Mehrfamilienhaus Pirna; Leck an Verteiler, Schaden an zwei Wohnungen.",
         "status": "GESCHLOSSEN", "seit": "2021-05-11", "reserve": 0.0, "bezahlt": 38200.0, "regress": 0.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": "MIT-00009", "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "EUR",
         "geschaedigter": "Wohnungseigentuemergemeinschaft Pirna",
         "positionen": [("RESERVE", 40000.0, "2020-12-07", None, "Erstreserve nach Bericht Sanierungsfirma"),
                        ("ZAHLUNG", 38200.0, "2021-05-06", "WEG Pirna", "Sanierungsrechnungen, Haftung 100 Prozent"),
                        ("RESERVE", 0.0, "2021-05-11", None, "geschlossen")]},
        {"id": "SCH-00000419", "vertrag": "VTR-00000401", "art": "HP_SACH", "ursache": "DACHARBEITEN_PV",
         "datum": "2024-09-17", "meldung": "2024-09-18", "kanal": "PORTAL", "plz": "01796", "land": "DE",
         "kurz": "Bei Photovoltaik-Montage werden Dachziegel und Unterspannbahn beschaedigt; Regen dringt ein, Schaden an Dachstuhl und Zimmerdecke. Taetigkeit im Formular: Dacharbeiten.",
         "status": "GESCHLOSSEN", "seit": "2024-11-05", "reserve": 0.0, "bezahlt": 27500.0, "regress": 0.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": "MIT-00009", "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "EUR",
         "geschaedigter": "Hauseigentuemer (Heidenau)",
         "positionen": [("RESERVE", 30000.0, "2024-09-19", None, "Erstreserve"),
                        ("ZAHLUNG", 27500.0, "2024-10-28", "Geschaedigter", "Dachdecker- und Malerrechnungen, SB 500; reguliert mit Hinweis auf Anzeigepflicht"),
                        ("RESERVE", 0.0, "2024-11-05", None, "geschlossen")]},
    ],
    "interaktionen": [
        {"id": "INT-00000419", "kanal": "EMAIL", "richtung": "AUSGEHEND", "zeit": "2024-10-08T14:30:00", "mitarbeiter": "MIT-00009", "vermittler": "VRM-00117",
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000419", "thread": "TH-00000419", "betreff": "Schaden SCH-00000419 Bergmann Gebaeudetechnik: Regulierung und Hinweis Anzeigepflicht", "sprache": "de",
         "sentiment": None,
         "text": "Sehr geehrte Damen und Herren,\n\nden Schaden vom 17.09.2024 (Dachziegel und Unterspannbahn bei Photovoltaik-Montage) regulieren wir mit EUR 27.500,00 abzueglich Selbstbehalt EUR 500,00.\n\nGleichzeitig weisen wir darauf hin, dass die Betriebsbeschreibung Ihrer Kundin vom Januar 2014 keine Dach- oder Photovoltaikarbeiten enthaelt. Die Aufnahme dieser Taetigkeit stellt eine Gefahrerhoehung dar, die uns gemaess Paragraph 23 VVG anzuzeigen gewesen waere. Wir bitten um eine aktualisierte Betriebsbeschreibung bis 15.11.2024. Bis dahin werden wir keine weiteren Schaeden aus Dacharbeiten ohne Einzelfallpruefung regulieren.\n\nMit freundlichen Gruessen\nAylin Demirci, Teamleiterin Schaden Haftpflicht DE"},
        {"id": "INT-00000420", "kanal": "EMAIL", "richtung": "EINGEHEND", "zeit": "2024-10-09T22:14:00", "mitarbeiter": "MIT-00009", "vermittler": None,
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000419", "thread": "TH-00000419", "betreff": "Re: Schaden SCH-00000419 Bergmann Gebaeudetechnik", "sprache": "de",
         "sentiment": "negativ",
         "text": "Frau Demirci,\n\nwir bauen seit Maerz Photovoltaik, das weiss unser Makler seit dem Fruehjahr. Ich habe das schon Ihrem Kollegen erklaert, als wir die Umsatzmeldung geschickt haben. Dass wir jetzt eine neue Betriebsbeschreibung brauchen, hoeren wir zum ersten Mal.\n\nWir liefern die Unterlagen ueber den Makler. Ich erwarte, dass die Regulierung des laufenden Schadens davon unberuehrt bleibt.\n\nMit freundlichen Gruessen\nKerstin Bergmann, Geschaeftsfuehrerin"},
        {"id": "INT-00000431", "kanal": "TELEFON", "richtung": "EINGEHEND", "zeit": "2025-08-19T11:20:00", "mitarbeiter": None, "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000402", "thread": "TH-00000431", "betreff": "Telefonnotiz: Rueckkaufswert Rente Bergmann", "sprache": "de",
         "sentiment": "neutral",
         "text": "Tel. Frau K. Bergmann, Kundenservice Leipzig, 6 Min. Fragt nach Rueckkaufswert und Moeglichkeit Beitragsfreistellung ihrer privaten Rentenversicherung (L-0207731), Grund Investitionen im Betrieb. Rueckkaufswert per 30.06.2025 genannt (EUR 31'840, Stornoabzug 3 Prozent). Auf Beitragsfreistellung als Alternative hingewiesen. Kundin will es mit Makler besprechen. Kein Auftrag."},
    ],
    "dokumente": [
        {"id": "DOK-00000401", "typ": "BETRIEBSBESCHREIBUNG", "richtung": "EINGEHEND", "format": "MD", "datum": "2024-11-28", "bezug": ("vertrag", "VTR-00000401"),
         "seiten": 5, "ocr": "GUT", "absender": "Elbtal Assekuranzmakler GmbH fuer Bergmann Gebaeudetechnik GmbH & Co. KG", "empfaenger": "Pfefferminz Versicherung AG, Niederlassung Deutschland",
         "titel": "Betriebsbeschreibung und Risikofragebogen Betriebshaftpflicht (Aktualisierung 2024)",
         "text": "Betrieb: Bergmann Gebaeudetechnik GmbH & Co. KG, Kupferring 18, 01796 Pirna. Gruendung 1992. Geschaeftsfuehrerin Kerstin Bergmann, Prokurist Ralf Neubauer.\n\nTaetigkeiten (Anteil am Umsatz):\n- Sanitaer-, Heizungs- und Klimainstallation (WZ 43.22)           62 Prozent\n- Waermepumpen inkl. Erdsonden-Anschluss                          12 Prozent\n- Photovoltaik-Montage auf Daechern inkl. Unterkonstruktion (neu seit 03/2024, WZ 43.21) 21 Prozent\n- Wartung und Notdienst                                             5 Prozent\n\nBeschaeftigte: 42 (davon 31 gewerblich, 6 Auszubildende). Subunternehmer: Geruestbau und Elektroanschluss PV (Anteil ca. 15 Prozent).\nUmsatz 2023: EUR 5.9 Mio.; Plan 2024: EUR 6.8 Mio.\n\nRisikofragen:\n- Arbeiten auf Daechern: JA (seit 03/2024), Absturzsicherung nach DGUV, Schulung nachgewiesen.\n- Heissarbeiten (Loeten, Schweissen): JA, Heissarbeitenerlaubnis-Schein vorhanden.\n- Auslandsanteil: NEIN.\n- Asbest: nur zertifizierte Entsorgung durch Dritte.\n- Schaeden der letzten 5 Jahre: 2020 Wasserschaden EUR 38'200; 2024 Dachschaden PV EUR 27'500.\n\nGewuenschte Deckung: Deckungssumme EUR 5 Mio., Taetigkeitsschaeden EUR 500'000 (Erhoehung auf 1 Mio. abgelehnt), Bausteine Umwelt-Basis, Schluesselverlust, Heissarbeiten neu."},
        {"id": "DOK-00000402", "typ": "BERATUNGSPROTOKOLL", "richtung": "INTERN", "format": "MD", "datum": "2024-11-28", "bezug": ("vertrag", "VTR-00000401"),
         "seiten": 2, "ocr": "GUT", "absender": "Elbtal Assekuranzmakler GmbH", "empfaenger": "Bergmann Gebaeudetechnik GmbH & Co. KG",
         "titel": "Beratungsdokumentation gemaess Paragraph 61 VVG",
         "text": "Anlass: Nachtrag zur Betriebshaftpflicht nach Aufnahme der Photovoltaik-Montage; Aufforderung des Versicherers nach Schaden vom 17.09.2024.\n\nWuensche und Beduerfnisse der Kundin: Vollstaendiger Versicherungsschutz fuer Dacharbeiten; Kosten begrenzen.\n\nEmpfehlung des Maklers:\n1. Betriebsbeschreibung aktualisieren (erfolgt).\n2. Baustein Heissarbeiten einschliessen (Zuschlag 8 Prozent). Empfohlen, von der Kundin angenommen.\n3. Sublimit Taetigkeitsschaeden von EUR 500'000 auf EUR 1 Mio. erhoehen (Zuschlag ca. EUR 380 p. a.). Empfohlen, von der Kundin abgelehnt (Begruendung: Kosten; bisherige Schaeden unter 500'000).\n4. Objektbezogene Bauleistungsversicherung fuer PV-Projekte ueber EUR 100'000. Empfohlen, Entscheid vertagt.\n\nHinweis erteilt: Bei Nichtanzeige weiterer Taetigkeitsaenderungen droht Leistungsfreiheit (Paragraphen 23 ff. VVG, vereinfacht dargestellt).\n\nUnterschriften: K. Bergmann, Makler J. K. (Elbtal Assekuranzmakler), 28.11.2024"},
        {"id": "DOK-00000403", "typ": "NACHTRAG", "richtung": "AUSGEHEND", "format": "MD", "datum": "2024-12-16", "bezug": ("vertrag", "VTR-00000401"),
         "seiten": 2, "ocr": "GUT", "absender": "Pfefferminz Versicherung AG, Niederlassung Deutschland", "empfaenger": "Bergmann Gebaeudetechnik GmbH & Co. KG",
         "titel": "Nachtrag Nr. 3 zum Versicherungsschein 40.612.384-1, wirksam 01.01.2025",
         "text": "Aenderungsgrund: Aktualisierung Betriebsbeschreibung, Aufnahme Photovoltaik-Montage, Einschluss Heissarbeiten.\n\n                                  bisher                       neu\nBetriebsart                       Sanitaer/Heizung/Klima       zusaetzlich PV-Montage (Dacharbeiten)\nRisikoklasse                      4                            4\nBemessungsgrundlage Umsatz        EUR 4'900'000                EUR 6'800'000\nBausteine                         Umwelt-Basis, Schluessel     zusaetzlich Heissarbeiten\nZuschlag Schadenquote 3 Jahre     0 Prozent                    10 Prozent\nJahresbeitrag netto               EUR 4'184.87                 EUR 5'320.52\nVersicherungsteuer 19 Prozent     EUR 795.13                   EUR 1'010.90\nJahresbeitrag brutto              EUR 4'980.00                 EUR 6'331.42\n\nDie uebrigen Bestimmungen bleiben unveraendert. Bedingungsgeneration HP-MODERN (AHB 2013, BBR 2015)."},
        {"id": "DOK-00000404", "typ": "UMSATZMELDUNG", "richtung": "EINGEHEND", "format": "MD", "datum": "2019-11-12", "bezug": ("vertrag", "VTR-00000401"),
         "seiten": 1, "ocr": "SCHLECHT", "absender": "Bergmann Gebaeudetechnik, R. Neubauer", "empfaenger": "Pfefferminz Versicherung AG",
         "titel": "Umsatzmeldung 2018 (E-Mail mit Excel-Anhang)",
         "text": "Sehr geehrte Damen und Herren,\n\nanbei die Umsatzmeldung fuer das Jahr 2018.\n\nUmsatz gesamt lt. beiliegender Aufstellung: EUR 4.600.000\n(Anmerkung Sachbearbeiter, handschriftlich am Rand: Bilanz HR-Auszug weist EUR 4.900.000 aus. Differenz 300.000 = ? Rueckfrage 20.11.19 an Makler, keine Antwort. Praemie vorlaeufig belassen.)\n\nMit freundlichen Gruessen\nRalf Neubauer, Prokurist"},
    ],
}

# ------------------------------------------------------------------------------------------------
# PTR-00000005 Elisabeth Vogt-Schnyder – Ablauf Kapitalversicherung, Bezugsrecht, Leibrente, Hundebiss
# ------------------------------------------------------------------------------------------------
AKTEN["PTR-00000005"] = {
    "schaeden": [
        {"id": "SCH-00000501", "vertrag": "VTR-00000501", "art": "LV_ABLAUF", "ursache": "ERLEBEN",
         "datum": "2019-06-09", "meldung": "2019-03-04", "kanal": "VERMITTLER", "plz": "4500", "land": "CH",
         "kurz": "Ablauf der gemischten Lebensversicherung PK-95 mit Alter 65. Bezugsberechtigter im Todesfall (Ehemann) vier Monate vor Ablauf verstorben; Erlebensfallleistung an die Versicherungsnehmerin.",
         "status": "GESCHLOSSEN", "seit": "2019-06-14", "reserve": 0.0, "bezahlt": 168420.0, "regress": 0.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": "MIT-00007", "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "CHF",
         "geschaedigter": None,
         "positionen": [("ZAHLUNG", 120000.0, "2019-06-12", "Versicherungsnehmerin", "Garantierte Erlebensfallsumme"),
                        ("ZAHLUNG", 41300.0, "2019-06-12", "Versicherungsnehmerin", "Laufende Ueberschussanteile, verzinslich angesammelt"),
                        ("ZAHLUNG", 7120.0, "2019-06-12", "Versicherungsnehmerin", "Schlussueberschuss")]},
        {"id": "SCH-00000510", "vertrag": "VTR-00000503", "art": "HP_PERSONEN", "ursache": "HUNDEBISS",
         "datum": "2022-08-30", "meldung": "2022-09-05", "kanal": "BRIEF", "plz": "4500", "land": "CH",
         "kurz": "Hund der Versicherungsnehmerin beisst Nachbarn in die Hand; Arztkosten CHF 640, gemeldet per Brief mit Arztrechnung.",
         "status": "GESCHLOSSEN", "seit": "2022-09-27", "reserve": 0.0, "bezahlt": 640.0, "regress": 0.0, "deckung": "GEDECKT",
         "ablehnung": None, "sb": "MIT-00008", "betrug_sichtbar": "KEIN", "betrug_wahr": False, "waehrung": "CHF",
         "geschaedigter": "Nachbar (Solothurn)",
         "positionen": [("RESERVE", 1500.0, "2022-09-06", None, "Erstreserve Personenschaden leicht"),
                        ("ZAHLUNG", 640.0, "2022-09-26", "Nachbar", "Arztrechnung Notfallstation, kein Selbstbehalt Altvertrag"),
                        ("RESERVE", 0.0, "2022-09-27", None, "geschlossen")]},
    ],
    "interaktionen": [
        {"id": "INT-00000501", "kanal": "BRIEF", "richtung": "EINGEHEND", "zeit": "2016-03-21T00:00:00", "mitarbeiter": "MIT-00007", "vermittler": "VRM-00004",
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000501", "thread": "TH-00000501", "betreff": "Frage zur Standmitteilung: sinkender Ueberschuss", "sprache": "de",
         "sentiment": "neutral",
         "text": "Sehr geehrte Damen und Herren der Pfefferminz Versicherung\n\nIch habe Ihre Standmitteilung vom 8. Maerz erhalten und mit den Vorjahren verglichen. Der Ueberschussanteil ist wieder gesunken, von 2.9 auf 2.5 Prozent. Mein verstorbener Vater hat mir immer gesagt, eine Lebensversicherung sei sicher. Ich bitte um eine verstaendliche Erklaerung, warum der Betrag jedes Jahr kleiner wird, und ob die garantierte Summe von 120'000 Franken davon betroffen ist.\n\nMit freundlichen Gruessen\nE. Vogt-Schnyder"},
        {"id": "INT-00000502", "kanal": "BRIEF", "richtung": "AUSGEHEND", "zeit": "2016-04-05T00:00:00", "mitarbeiter": "MIT-00007", "vermittler": "VRM-00004",
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000501", "thread": "TH-00000501", "betreff": "Ihre Frage zur Ueberschussbeteiligung", "sprache": "de",
         "sentiment": None,
         "text": "Sehr geehrte Frau Vogt-Schnyder\n\nVielen Dank fuer Ihren Brief. Ihre Sorge ist verstaendlich, deshalb gerne in Ruhe:\n\nDie garantierte Summe von CHF 120'000 ist fest zugesagt und aendert sich nicht. Ihr Vertrag aus dem Jahr 1995 rechnet mit einem technischen Zins von 3.5 Prozent; das ist heute deutlich mehr, als am Kapitalmarkt sicher zu erzielen ist. Der Ueberschuss ist der Teil, den wir zusaetzlich zur Garantie erwirtschaften. Weil die Zinsen seit Jahren tief sind, faellt dieser Zusatz kleiner aus. Bei Ablauf 2019 erhalten Sie die garantierte Summe, die bis dahin angesammelten Ueberschuesse und einen Schlussueberschuss.\n\nIhre Beraterin in der Agentur Solothurn erlaeutert Ihnen die Zahlen gerne persoenlich.\n\nMit freundlichen Gruessen\nRuth Amrein, Leistungspruefung Leben"},
        {"id": "INT-00000505", "kanal": "TELEFON", "richtung": "EINGEHEND", "zeit": "2019-03-04T14:00:00", "mitarbeiter": "MIT-00007", "vermittler": "VRM-00004",
         "bezug_typ": "SCHADEN", "bezug_id": "SCH-00000501", "thread": "TH-00000505", "betreff": "Telefonnotiz Tochter Andrea Vogt: Ablauf und Todesfall Vater", "sprache": "de",
         "sentiment": "neutral",
         "text": "Tel. Frau Andrea Vogt (Tochter der VN), 12 Min. Vater Walter Vogt am 14.02.2019 verstorben, Todesfallmeldung ueber Agentur bereits erfolgt (eigener Vertrag L-0031186). Fragt, ob die Kinder aus dem Vertrag der Mutter (L-0031187, Ablauf 09.06.2019) 'etwas bekommen', weil der Vater Beguenstigter war. Erklaert: Bezugsrecht gilt nur im Todesfall der versicherten Person; Mutter erlebt den Ablauf, Leistung geht an sie als VN. Tochter erleichtert. Wunsch: Beratung zur Verwendung des Kapitals (Rente?). Termin Agentur vereinbart."},
        {"id": "INT-00000512", "kanal": "BRIEF", "richtung": "EINGEHEND", "zeit": "2025-02-17T00:00:00", "mitarbeiter": "MIT-00013", "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000502", "thread": "TH-00000512", "betreff": "Ist meine Rente nach der Fusion sicher?", "sprache": "de",
         "sentiment": "neutral",
         "text": "Sehr geehrte Damen und Herren der Pfefferminz Versicherung\n\nIn der Zeitung habe ich gelesen, dass die Pfefferminz mit einer Firma aus Berlin zusammengelegt wurde und jetzt anders heisst. Ich beziehe seit 2019 eine Rente von Ihnen (Vertrag L-0221904). Bitte bestaetigen Sie mir schriftlich, dass meine Rente in der bisherigen Hoehe weiterbezahlt wird und dass mein Vertrag bei einer Schweizer Gesellschaft bleibt.\n\nIch bitte um Antwort per Brief, ich habe keine E-Mail.\n\nMit freundlichen Gruessen\nE. Vogt-Schnyder"},
        {"id": "INT-00000513", "kanal": "BRIEF", "richtung": "AUSGEHEND", "zeit": "2025-02-24T00:00:00", "mitarbeiter": "MIT-00013", "vermittler": None,
         "bezug_typ": "VERTRAG", "bezug_id": "VTR-00000502", "thread": "TH-00000512", "betreff": "Ihre Rente bleibt unveraendert", "sprache": "de",
         "sentiment": None,
         "text": "Sehr geehrte Frau Vogt-Schnyder\n\nVielen Dank fuer Ihren Brief. Ihre Rente wird unveraendert in der bisherigen Hoehe von CHF 512.50 monatlich zuzueglich Ueberschussrente weiterbezahlt. Ihr Vertrag bleibt bei der Pfefferminzia Leben AG mit Sitz in Olten, die von der FINMA beaufsichtigt wird. Der Zusammenschluss betrifft den Namen und die Organisation, nicht Ihre vertraglichen Anspruueche.\n\nSollten Sie Fragen haben, erreichen Sie uns weiterhin telefonisch unter der gewohnten Nummer.\n\nMit freundlichen Gruessen\nPfefferminzia Versicherungen AG, Kundenservice Olten\nDario Bianchi"},
    ],
    "dokumente": [
        {"id": "DOK-00000501", "typ": "STANDMITTEILUNG", "richtung": "AUSGEHEND", "format": "MD", "datum": "2016-03-08", "bezug": ("vertrag", "VTR-00000501"),
         "seiten": 2, "ocr": "GUT", "absender": "Pfefferminz Leben AG", "empfaenger": "Elisabeth Vogt-Schnyder",
         "titel": "Standmitteilung per 31.12.2015, Police L-0031187",
         "text": "Gemischte Lebensversicherung, Tarif PK-95, Beginn 01.07.1995, Ablauf 09.06.2019\nVersicherungsnehmerin und versicherte Person: Elisabeth Vogt-Schnyder, geb. 09.06.1954\nBezugsberechtigt im Todesfall: Walter Vogt, ersatzweise die Kinder zu gleichen Teilen\n\nGarantierte Erlebensfallsumme            CHF 120'000.00\nTodesfallsumme                           CHF 120'000.00\nJahrespraemie                            CHF   4'236.00\nTechnischer Zins                                3.50 Prozent\n\nDeckungskapital per 31.12.2015           CHF  96'412.00\nAngesammelte Ueberschussanteile          CHF  35'870.00\nUeberschussanteil 2015 (laufend)              2.50 Prozent (Vorjahr 2.90 Prozent)\nRueckkaufswert per 31.12.2015            CHF 128'340.00 (inkl. Ueberschuesse)\n\nPrognose Ablaufleistung (unverbindlich, bei gleichbleibendem Ueberschuss): CHF 166'000 bis 171'000"},
        {"id": "DOK-00000502", "typ": "ABLAUFABRECHNUNG", "richtung": "AUSGEHEND", "format": "MD", "datum": "2019-06-12", "bezug": ("schaden", "SCH-00000501"),
         "seiten": 1, "ocr": "GUT", "absender": "Pfefferminz Leben AG, Leistungspruefung", "empfaenger": "Elisabeth Vogt-Schnyder",
         "titel": "Ablaufabrechnung Police L-0031187",
         "text": "Ablauf per 09.06.2019 (Alter 65)\n\nGarantierte Erlebensfallsumme               CHF 120'000.00\nAngesammelte laufende Ueberschussanteile     CHF  41'300.00\nSchlussueberschuss                            CHF   7'120.00\nAblaufleistung total                         CHF 168'420.00\n\nBezugsrechtspruefung: Der im Todesfall bezugsberechtigte Ehemann Walter Vogt ist am 14.02.2019 verstorben. Da die versicherte Person den Ablauf erlebt, ist das Todesfall-Bezugsrecht gegenstandslos; die Erlebensfallleistung steht der Versicherungsnehmerin zu (AVB PK-95 Art. 9 Abs. 2).\n\nSteuern: Kapitalleistung aus Saeule 3b, Abschluss vor Alter 66, Laufzeit ueber 5 Jahre, Auszahlung nach Alter 60: einkommenssteuerfrei (vereinfachte Darstellung, kantonale Praxis vorbehalten).\n\nAuszahlung am 12.06.2019 auf Konto Oltener Kantonalbank, IBAN CH.. (in der Akte).\n\nSachbearbeiterin: R. Amrein"},
        {"id": "DOK-00000503", "typ": "OFFERTE", "richtung": "AUSGEHEND", "format": "MD", "datum": "2019-07-18", "bezug": ("vertrag", "VTR-00000502"),
         "seiten": 3, "ocr": "GUT", "absender": "Pfefferminz Leben AG, Agentur Solothurn", "empfaenger": "Elisabeth Vogt-Schnyder",
         "titel": "Offerte Leibrente RentePlus mit Einmalpraemie CHF 150'000",
         "text": "Sofort beginnende Leibrente, Tarif PL-2017, Rentenbeginn 01.09.2019\nEinmalpraemie                              CHF 150'000.00\nStempelabgabe 2.5 Prozent (Saeule 3b)      CHF   3'750.00\nGesamtbetrag                               CHF 153'750.00\n\nGarantierte Monatsrente lebenslang         CHF     512.50\nUeberschussrente (nicht garantiert, 2019)  CHF      31.20\nRentengarantiezeit 10 Jahre: Bei Tod vor dem 31.08.2029 wird die Rente bis dahin an die Erben weiterbezahlt.\n\nHinweis zu Ihrer Frage vom 12.07.: Die Stempelabgabe von 2.5 Prozent faellt auf Einmalpraemien in der freien Vorsorge (Saeule 3b) an. Sie ist eine Bundesabgabe, nicht eine Gebuehr der Versicherung. Bei laufenden Praemien entfaellt sie.\n\nSteuern im Rentenbezug: Leibrenten aus Saeule 3b sind zu 40 Prozent als Einkommen steuerbar (vereinfachte Darstellung).\n\nBeraterin: Agentur Solothurn"},
        {"id": "DOK-00000504", "typ": "SCHADENMELDUNG", "richtung": "EINGEHEND", "format": "MD", "datum": "2022-09-05", "bezug": ("schaden", "SCH-00000510"),
         "seiten": 1, "ocr": "HANDSCHRIFT", "absender": "Elisabeth Vogt-Schnyder", "empfaenger": "Pfefferminz Versicherung AG",
         "titel": "Schadenmeldung Hundebiss (handschriftlicher Brief)",
         "text": "Solothurn, 5. September 2022\n\nSehr geehrte Damen und Herren der Pfefferminz Versicherung\n\nAm 30. August hat mein Hund Rex (Mischling, 9 Jahre) unseren Nachbarn Herrn K. beim Gartenzaun in die rechte Hand gebissen. Herr K. wollte ihn streicheln, Rex hat sich erschrocken. Herr K. war auf der Notfallstation im Buergerspital, die Wunde wurde gereinigt und geklammert. Ich lege die Arztrechnung ueber Fr. 640.- bei (Beilage 1) und bitte Sie, den Betrag an Herrn K. zu ueberweisen. Seine Kontoangaben finden Sie auf Beilage 2.\n\nRex ist bei Ihnen in meiner Haftpflichtversicherung Nr. 40.018.829-3 mitversichert, wie mir Frau A. von der Agentur bestaetigt hat.\n\nMit freundlichen Gruessen\nE. Vogt-Schnyder"},
    ],
}
